#pragma config(Sensor, dgtl12, green,          sensorLEDtoVCC)
#pragma config(Motor,  port2,           rightmotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftmotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           ServoMotor,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Project Title:
Team Members: Dylan, Charles, Cedric, Julio
Date: 2/7/19
Section: A3_1_2_Part1


Task Description:


Pseudocode:

*/

task main()
{
	turnLEDOff(green);
	wait(1);
	turnLEDOn(green);
	wait(2);
	turnLEDOff(green);
	wait(3);
	turnLEDOn(green);
	wait(4);
	turnLEDOff(green);
}
